### ISSUE TITLE
Examples link broken

### ISSUE THREAD

**Issue by photonstorm** [JTronLabs/phaser-ui#2]
Nice package :) Sadly the link to view the examples online is broken as the domain hasn't been renewed.

**Comment by JarLowrey** [comment]
Wow thanks Rich! I appreciate you checking it out and letting me know. Ended up going down a rabbit hole as I updated some dependencies and then had a bunch of issues with `npm install` for nested projects, GitHub/GitLab hosting and custom domains...

I had moved my portfolio repo to GitLab hosting which means the domain's DNS records were breaking the link, even if I hadn't let the domain expire. So I had to delete my old GitHub `jarlowrey.github.io` repo that I had forgotten about, and fix some other broken links in some old projects.

Anyways, the link & project are now working, viewable here - https://jarlowrey.github.io/phaser-ui/test/dist/

**Comment by JarLowrey** [comment]
https://github.com/JarLowrey/phaser-ui/commit/a50a5af759a7be4b16a052a979b3647cd70b8ec9
https://github.com/JarLowrey/phaser-ui/commit/ce0836c41aaf7f41da398ce9ec36d68bc65a29ab
https://github.com/JarLowrey/phaser-ui/commit/c710eb8db67fefb276e09024ebc205901be55a9e
https://github.com/JarLowrey/phaser-ui/commit/5ba5007fdc5fe94ac1818785165adb470a2801e0

**Comment by photonstorm** [comment]
Neat :) I featured the package on the Phaser web site this week, so wanted to give you a heads up!

**Comment by JarLowrey** [comment]
Hey thanks!
